tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/x11'

# CLI
brew 'coreutils'
brew 'macvim'
brew 'ssh-copy-id'
brew 'tmux'
brew 'vim'
brew 'wget'
cask 'iterm2'

# Middleware
brew 'mas'
cask 'java'

# Desktop
mas 'Xcode', id: 497799835
mas 'The Unarchiver', id: 425424353
mas 'Caffeine', id: 411246225
