tap 'homebrew/php'

# PHP 7.0
# brew 'homebrew/php/php56' # old
brew 'homebrew/php/php70'
brew 'homebrew/php/composer'

# Databases
brew 'sqlite'
brew 'mariadb'
brew 'postgresql'

cask 'virtualbox'
cask 'vagrant'
cask 'vagrant-manager'
