tap 'caskroom/cask'
tap 'osx-cross/avr'

brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'libftdi0'
brew 'avrdude'
brew 'cmake'
brew 'dfu-programmer'
brew 'picocom'
brew 'osx-cross/avr/avr-binutils'
brew 'osx-cross/avr/avr-gcc'
brew 'osx-cross/avr/avr-libc'
